# Generated by Django 5.0.6 on 2024-06-10 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogApp', '0002_remove_articulo_categoria_articulo_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articulo',
            old_name='fechaActualizacion',
            new_name='fecha_actualizacion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='fechaCreacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='imagenPrincipal',
            new_name='imagen_principal',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='imagenSecundaria',
            new_name='imagen_secundaria',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='imagenTerciaria',
            new_name='imagen_terciaria',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='videoPrincipal',
            new_name='video_principal',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='videoSecundario',
            new_name='video_secundario',
        ),
        migrations.RenameField(
            model_name='articulo',
            old_name='videoTerciario',
            new_name='video_terciario',
        ),
    ]
